CREATE TABLE "topu_v1_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "topu_v1_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "topu_v1_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "topu_v1_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "topu_v1_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "topu_v1_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "topu_v1_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "topu_v1_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "topu_v1_account" ADD CONSTRAINT "topu_v1_account_user_id_topu_v1_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."topu_v1_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "topu_v1_post" ADD CONSTRAINT "topu_v1_post_created_by_topu_v1_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."topu_v1_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "topu_v1_session" ADD CONSTRAINT "topu_v1_session_user_id_topu_v1_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."topu_v1_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "topu_v1_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "topu_v1_post" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "name_idx" ON "topu_v1_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "topu_v1_session" USING btree ("user_id");